spring:
  application:
    name: DADUM-Server

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/dadum?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul}
    username: ${SPRING_DATASOURCE_USERNAME:dadum}
    password: ${SPRING_DATASOURCE_PASSWORD:dadum1234}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    hibernate:

      ddl-auto: ${JPA_DDL_AUTO:none}
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: Asia/Seoul

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile

jwt:
  secret: ${JWT_SECRET:01234567890123456789012345678901}
  access-token-expiration-seconds: ${JWT_ACCESS_TOKEN_EXPIRATION_SECONDS:3600}
  refresh-token-expiration-seconds: ${JWT_REFRESH_TOKEN_EXPIRATION_SECONDS:1209600}
